export * from './Login/Login.page'
export * from './Forgot/Forgot.page'
export * from './UpdateForgotPassword/UpdateForgotPassword.page'
export * from './Orders/Orders.page'
export * from './Users/Users.page'
export * from './OrderDetail/OrderDetail.page'